Repository KakaoTech-team20/dev-guidelines, pull requests merged in 2024-07, with the labels that each got.

#6 feature: 조현 기능 추가
  Jo.Kim
Labels: documentation, enhancement

#4 docs: 자기소개입니다
  Lyle/introduce.md
Labels: documentation, enhancement

#7 Feature/andrew branch test
  pyramid.py
Labels: enhancement

#9 Revert "feature: 조현 기능 추가"
  Jo.Kim
Labels: documentation, enhancement

#5 Crystal의 PR 연습
  crystal/hello.txt
  crystal/world
Labels: documentation

#8 Reggie의 PR 연습
  Reggie/reggie.md
Labels: documentation, enhancement
